#!/usr/bin/python3
'''module'''


class BaseGeometry():
    '''BaseGeometry class'''
    def area(self):
        '''area'''
        raise Exception("area() is not implemented")

    def integer_validator(self, name, value):
        '''integer_validator method'''
        pass
