#!/usr/bin/python3

"""Module built for Python 0x07 task 0.
"""

"""Module built for Python 0x07 task 0.
"""

"""Module built for Python 0x07 task 0.
"""
"""Module built for Python 0x07 task 0.
"""
def add_integer(a, b=98):
    """Function that adds two integers.

    Args:
        a ((int, (float)): first arg to add to sum.
        b ((int, (float)): second arg to add to sum. Defaults to 98.

    Returns: sum of both values.

    """
"""Module built for Python 0x07 task 0.
"""
    if isinstance(a, float):
        a = int(a)
    elif not isinstance(a, int):
        raise TypeError("a must be an integer")

    if isinstance(b, float):
        b = int(b)
    elif not isinstance(b, int):
        raise TypeError("b must be an integer")
    return (a + b)
