#!/usr/bin/python3

def main():
    import sys

    n = len(sys.argv)

    if n == 0:
        print("0 arguments.")
        sysd.exit(1)

    if n == 1:
         print("1 argument:")
    else:
        print("{:d} arguments:".format(n - 1))
    for i in range(1, n):
        print("{}: {}".format(i, sys.argv[i]))


if __name__ == '__main__':
    main()
